do_not_merge:
  - 新宿
  - 渋谷
  - 東京

access_points:
  新宿:
    - label: 新宿駅 東口寄り
      lat: 35.690455
      lng: 139.700564
  渋谷:
    - label: 渋谷駅 ハチ公口寄り
      lat: 35.659500
      lng: 139.700464
  池袋:
    - label: 池袋駅 東口寄り
      lat: 35.730278
      lng: 139.711389
  品川:
    - label: 品川駅 高輪口寄り
      lat: 35.628471
      lng: 139.739345
  東京:
    - label: 東京駅 丸の内中央口寄り
      lat: 35.681236
      lng: 139.767125
  中野:
    - label: 中野駅 北口寄り
      lat: 35.705749
      lng: 139.665722
  目黒:
    - label: 目黒駅 西口寄り
      lat: 35.633998
      lng: 139.715828
  恵比寿:
    - label: 恵比寿駅 西口寄り
      lat: 35.646690
      lng: 139.710106
