name: RealEstateApp
options:
  bundleIdPrefix: com.hanawa.realestate
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "12.9.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"          # iPhone only
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0.0"

targets:
  RealEstateApp:
    type: application
    platform: iOS
    sources:
      - path: RealEstateApp
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseMessaging
      - package: GoogleSignIn
        product: GoogleSignIn
    info:
      path: RealEstateApp/Info.plist
      properties:
        CFBundleDisplayName: "物件情報"
        LSApplicationCategoryType: "public.app-category.lifestyle"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        BGTaskSchedulerPermittedIdentifiers:
          - "com.hanawa.realestate.app.refresh"
        UIBackgroundModes:
          - fetch
          - remote-notification
        NSCameraUsageDescription: "内見時の物件写真撮影に使用します"
        NSPhotoLibraryUsageDescription: "内見写真の保存・読み込みに使用します"
        NSLocationWhenInUseUsageDescription: "地図上で現在地を表示するために使用します"
        LSApplicationQueriesSchemes:
          - comgooglemaps
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - "com.googleusercontent.apps.481688023840-pd1prakenbuqgl1phfpdgkf2cghurak6"
    entitlements:
      path: RealEstateApp/RealEstateApp.entitlements
      properties:
        com.apple.developer.usernotifications: true
        aps-environment: $(APS_ENVIRONMENT)
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hanawa.realestate.app
        SWIFT_EMIT_LOC_STRINGS: "YES"
      configs:
        Debug:
          APS_ENVIRONMENT: development
        Release:
          APS_ENVIRONMENT: production
