name: RealEstateApp
options:
  bundleIdPrefix: com.hanawa.realestate
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  defaultConfig: Debug

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "12.9.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"          # iPhone only
    CURRENT_PROJECT_VERSION: "1"
    MARKETING_VERSION: "1.0.0"

targets:
  RealEstateApp:
    type: application
    platform: iOS
    sources:
      - path: RealEstateApp
        excludes:
          - "**/.DS_Store"
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.hanawa.realestate.app
        SWIFT_EMIT_LOC_STRINGS: "YES"
    info:
      path: RealEstateApp/Info.plist
      properties:
        CFBundleDisplayName: "物件情報"
        LSApplicationCategoryType: "public.app-category.lifestyle"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        BGTaskSchedulerPermittedIdentifiers:
          - "com.hanawa.realestate.app.refresh"
        UIBackgroundModes:
          - fetch
    entitlements:
      path: RealEstateApp/RealEstateApp.entitlements
      properties:
        com.apple.developer.usernotifications: true
